apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: newman-junit
spec:
  interval: 120
  severity: high
  junit:
    - testResults: "/tmp/"
      name: junit-newman
      display:
        template: |
          ✅ {{.results.passed}} ❌ {{.results.failed}} in 🕑 {{.results.duration}}
          {{  range $r := .results.suites}}
          {{- if gt (conv.ToInt $r.failed)  0 }}
            {{$r.name}} ✅ {{$r.passed}} ❌ {{$r.failed}} in 🕑 {{$r.duration}}
          {{- end }}
          {{- end }}
      spec:
        containers:
          - name: newman
            image: ghcr.io/flanksource/canary-newman:latest
            command: ["/start.sh"]
