apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: cert-manager
spec:
  interval: 120
  severity: high
  kubernetes:
    - name: cert-manager-check
      icon: cert-manager
      kind: Certificate
      transform:
        javascript: |
          JSON.stringify(results.map(function(result) {
            var r = result.Object
            var pass = false
            var message = ''
            for (condition in r.status.conditions) {
              message += r.status.conditions[condition].type + ':' + r.status.conditions[condition].status + ' '
              if (r.status.conditions[condition].type == "Ready" && r.status.conditions[condition].status == "True") {
                pass = true
              }
            }
            return {
              name: r.metadata.name,
              namespace: r.metadata.namespace,
              pass: pass,
              labels: r.metadata.labels,
              icon: 'cert-manager',
              message: message,
            }
          }))
