name: docker

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Github Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push playwright
        uses: docker/build-push-action@v4
        with:
          context: playwright/
          push: true
          tags: ghcr.io/flanksource/canary-playwright:latest

      - name: Build and push newman
        uses: docker/build-push-action@v4
        with:
          context: newman/
          push: true
          tags: ghcr.io/flanksource/canary-newman:latest

      - name: Build and push k6
        uses: docker/build-push-action@v4
        with:
          context: k6/
          push: true
          tags: ghcr.io/flanksource/canary-k6:latest
